## Project information
site_name: HfcQGIS
site_url: https://example.com/
site_description: Help funzioni calcolatore di campi di QGIS

## Repository
repo_name: HfcQGIS_md
repo_url: https://github.com/gbvitrano/HfcQGIS_md
edit_uri: edit/master/docs/ #disables edit button

# Copyright
copyright: CC-BY-SA-4.0 License

## Page tree
nav:
    - Calcolatore di Campi:
      - bla bla: bla.md
    - Novità:
        - Novità: bla.md
        - Novità rilevanti introdotte in QGIS 3.0 Girona 23/02/2018: bla.md
        - Novità rilevanti introdotte nella 3.2: bla.md
        - Novità rilevanti introdotte in QGIS 3.4 LTR 26/10/2018: bla.md
        - Novità rilevanti introdotte in QGIS 3.6 22/02/2019: bla.md
        - Novità rilevanti introdotte nella 3.8 21/06/2019: bla.md
        - Novità rilevanti introdotte in QGIS 3.10 25/10/2019: bla.md
        - Novità rilevanti introdotte in QGIS 3.12 21/02/2020: bla.md
        - Novità rilevanti introdotte in QGIS 3.14 19/06/2020: bla.md
        - Novità rilevanti introdotte in QGIS 3.16 23/10/2020: bla.md
        - Novità rilevanti introdotte in QGIS 3.18 22/02/2021: bla.md
        - Novità rilevanti introdotte in QGIS 3.20 21/06/2021: bla.md          
    - Elenco funzioni:
       - bla bla: bla.md
       - bla bla: bla.md
       - bla bla: bla.md
       - bla bla: bla.md
    - Mettiti alla prova con le espressioni di QGIS:
       - Provaci Tu: bla.md  
    - Corso di Formazione:
       - Corso di Formazione: bla.md
    - OpenDataSicilia:
        - OpenDataSicilia: bla.md
    -  Lavora con Noi:
        - Contribuire a HfcQGIS: bla.md
        - Supporter: bla.md
        - Parlano di noi: bla.md
    - Informativa privacy estesa:
        - Privacy Policy: bla.md

## Configuration
theme:
  name: material
 # custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: it
  features:
    - navigation.tabs
  palette:
    primary: indigo
    accent: purple
  font:
    text: Roboto
    code: Roboto Mono
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: HfcQGIS  # top left header logo
  favicon: img/favicon_h.ico #browser tab logo

## Plugins
plugins:
  - search
  - autolinks
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_source: true
            show_category_heading: true
          selection:
            filters:
              - "!^_"  # exlude all members starting with _
      watch:
        - src/my_library

## Custom theme additions
extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css

## Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      baselevel: 1
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - mkdocs-click

google_analytics:
  - 'UA-122084242-1'
  - 'auto'
