## Project information
site_name: HfcQGIS
site_url: https://hfcqgis-md.readthedocs.io/it/latest
site_description: Help funzioni calcolatore di campi di QGIS
site_author: OpenDataSicilia

## Repository
repo_name: HfcQGIS_md
repo_url: https://github.com/gbvitrano/HfcQGIS_md
edit_uri: edit/main/docs/ #disables edit button

# Copyright
copyright: OpenDataSicilia | CC-BY-SA-4.0 License

## Social Media
extra:
  social:
    - icon: fontawesome/solid/home
      link: https://hfcqgis-md.readthedocs.io/
      name: Home Page
    - icon: fontawesome/brands/twitter
      link: http://twitter.com/opendatasicilia
      name: account twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/opendatasicilia/
      name: gruppo facebook
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gbvitrano/HfcQGIS_md/
      name: Repoisitory GitHub
    - icon: fontawesome/brands/telegram
      link: http://twitter.com/opendatasicilia
      name: gruppo Telegram
    - icon: fontawesome/solid/envelope
      link: https://groups.google.com/forum/#!forum/opendatasicilia
      name: mailing list OpenDataSicilia
  analytics:
    provider: google
    property: UA-122084242-1
    
## Configuration
theme:
  name: material
  custom_dir: docs/override
  # 404 page
  static_templates:
    - 404.html
  palette:
    scheme: preference
  language: it
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    primary: green
    accent: red
  font:
    text: Lato
    code: Roboto Mono
  favicon: img/favicon.ico
  icon:
  logo: hfc
  
plugins:
- search
- mkdocstrings
- autolinks

markdown_extensions:
- toc:
        permalink: ↵
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
      

## Custom theme additions
extra_javascript:
   - stylesheets/extra.js
        
extra_css:
  # - stylesheets/extra.css      
   - stylesheets/homestyles.css 
      
 ## Page tree
nav:
    - Home: index.md
    - Calcolatore di Campi:
       - Calcolatore di Campi: calcolatore_campi/field_calc.md
       - Concetti fondamentali: calcolatore_campi/concetti.md
       - Interfaccia calcolatore di campi: calcolatore_campi/interfaccia.md
       - Operatori interfaccia: calcolatore_campi/operatori.md
       - Concetti fondamentali sulla tabella attributi: calcolatore_campi/tabella_attributi.md
    - Novità:
       - Novità rilevanti introdotte in QGIS 3.20 21/06/2021: release/novita_320.md   
       - Novità rilevanti introdotte in QGIS 3.18 22/02/2021: release/novita_318.md
       - Novità rilevanti introdotte in QGIS 3.16 23/10/2020: release/novita_316.md
       - Novità rilevanti introdotte in QGIS 3.14 19/06/2020: release/novita_314.md
       - Novità rilevanti introdotte in QGIS 3.12 21/02/2020: release/novita_312.md
       - Novità rilevanti introdotte in QGIS 3.10 25/10/2019: release/novita_310.md
       - Novità rilevanti introdotte nella 3.8 21/06/2019: release/novita_38.md
       - Novità rilevanti introdotte in QGIS 3.6 22/02/2019: release/novita_36.md
       - Novità rilevanti introdotte in QGIS 3.4 LTR 26/10/2018: release/novita_34.md
       - Novità rilevanti introdotte nella 3.2: release/novita_32.md
       - Novità rilevanti introdotte in QGIS 3.0 Girona 23/02/2018: release/novita_30.md
    - Elenco funzioni:
        - bla bla:
          - bla bla: bla.md
          - bla bla: bla.md
        - bla bla: bla.md
    - Esempi: 
        - Uso delle funzioni: esempi/lista_esempi.md
        - Esempi:
           - Campo area: esempi/add_col_area.md
           - Campi coordinate: esempi/add_coord_xy.md
           - Campo virtuale: esempi/add_campo_virtuale.md
           - Campo quota z: esempi/add_col_z.md
           - Etichettare: esempi/etichette.md
           - Aggiornare geometria: esempi/agg_geom.md
           - Conversione: esempi/conversione.md
           - Tematizzare: esempi/tematizzare.md
           - Legenda: esempi/espressione_regolare.md
           - Selezione: esempi/select_with_aggregate.md
           - Core area: esempi/core_area.md
           - Sposta etichette: esempi/sposta_etichetta_linea.md
           - Conteggio valori: esempi/conteggio.md
           - Centroidi linee curve: esempi/centroid_linee.md
           - Conta i punti nel poligono: esempi/conta_punti_in_poligono.md
           - Somma lunghezze nel poligono: esempi/somma_lunghezze_nel_poligono.md
           - Conta punti nel poligono per categorie: esempi/punti_in_poligoni_categorie.md
           - Nascondi etichette: esempi/nascondi_etichette.md
           - Calcolo area poligoni nel reticolo: esempi/calcolo_area_poligoni_reticolo.md
           - Spatial join: esempi/spatial_join.md
           - Unica label: esempi/unica_etichetta_più_poligoni.md
           - Elenco comuni: esempi/elenco_comuni_attraversati_fiume.md
           - Rotazione pattern lineare: esempi/rotazione_pattern.md
           - Numerazione poligoni in base a relazione spaziale: esempi/numerazione_poligoni_rel_spaziale.md
           - Assegnare categoria prevalente: esempi/assegnare_cat_prevalente.md
           - Creare Hub lines: esempi/hub_lines.md
           - Aggrega con SR differenti: esempi/aggregare_con_sr_differenti.md
           - Distanze progressive chilometriche: esempi/distanze_progressive_chilometriche.md
           - Aggregare elementi adiacenti: esempi/aggregare_elementi_contigui.md
           - Linea minima distanza tra due punti: esempi/linea_min_distanza.md
           - Creare campo somma cumulativa: esempi/add_campo_sum_cumulativo.md
           - Aggiungere punto a linea: esempi/aggiungere_punto_a_linea.md
           - Drilldown form multiple: esempi/drilldown_form_multiple.md
           - Selezionare primi n valori: esempi/selezionare_primi_n_valori.md
           - Generalizzare isoipse: esempi/generalizzare_linee.md
           - Campo coord in lat lon: esempi/campo_coord_in_lat_lon.md
           - Calcolo incrementi giornalieri: esempi/calcolo_incrementi_giornalieri.md
           - Tracciare un grafico: esempi/tracciare_grafico_generatore_geometrie.md
           - Elenco ordinato di Comuni: esempi/elenco_ordinato_comuni_attraversati.md
           - Etichettare con chiave-valore: esempi/etichettare_chiave_valore.md
           - Etichettare itinerario con elenco ordinato Comuni: esempi/etichettare_itinerario_elenco_comuni_attraversati.md
           - Etichette formattate diversi stili: esempi/etichette_formattate_diversi_stili.md
           - Selezionare vertici duplicati: esempi/select_duplicate_vertices.md
           - Conteggio caratteri diversi: esempi/conteggio_caratteri_diversi.md
           - Distanza minima tra due vettori: esempi/linea_min_distanza2.md
           - Lunghezze segmenti di un poligono: esempi/lunghezze_segmenti_poligono.md
           - Fill-down con QGIS: esempi/fill-down.md
           - Finestra temporale: esempi/finestra_temporale.md
           - Rotazione simbolo parallelo ad una linea: esempi/rotazione_simbolo_parallelo_linea.md
        - Provaci tu: mettiti_alla_prova.md   
    - Corso di Formazione: corso_formazione/corso_di_formazione.md
    -  Lavora con Noi:
        - Supporter: supporter.md
        - Parlano di noi: parlano_di_noi.md
        - Contribuire a HfcQGIS: contributing.md
    - Creditis:
        - OpenDataSicilia: ods.md    
        - Autore HfcQGIS: autore.md
        - Traduzione: traduzione.md
        - Disclaimer: disclaimer.md
        - Informativa privacy estesa: privacy.md       