## Project information
site_name: HfcQGIS
site_url: https://example.com/
site_description: Help funzioni calcolatore di campi di QGIS

## Repository
repo_name: HfcQGIS_md
repo_url: https://github.com/gbvitrano/HfcQGIS_md
edit_uri: edit/master/docs/ #disables edit button

# Copyright
copyright: CC-BY-SA-4.0 License

## Social Media
extra:
  social:
    - icon: fontawesome/solid/home
      link: http://opendatasicilia.it/
    - icon: fontawesome/brands/twitter
      link: http://opendatasicilia.it/
    - icon: fontawesome/brands/linkedin
      link: http://opendatasicilia.it/
    - icon: fontawesome/brands/github-alt
      link: http://opendatasicilia.it/
    - icon: fontawesome/brands/docker
      link: http://opendatasicilia.it/
    - icon: fontawesome/solid/envelope
      link: mailto:support@ods.com

## Page tree
nav:
    - Calcolatore di Campi:
      - bla bla: bla.md
    - Novità:
        - Novità: bla.md
        - Novità rilevanti introdotte in QGIS 3.0 Girona 23/02/2018: bla.md
        - Novità rilevanti introdotte nella 3.2: bla.md
        - Novità rilevanti introdotte in QGIS 3.4 LTR 26/10/2018: bla.md
        - Novità rilevanti introdotte in QGIS 3.6 22/02/2019: bla.md
        - Novità rilevanti introdotte nella 3.8 21/06/2019: bla.md
        - Novità rilevanti introdotte in QGIS 3.10 25/10/2019: bla.md
        - Novità rilevanti introdotte in QGIS 3.12 21/02/2020: bla.md
        - Novità rilevanti introdotte in QGIS 3.14 19/06/2020: bla.md
        - Novità rilevanti introdotte in QGIS 3.16 23/10/2020: bla.md
        - Novità rilevanti introdotte in QGIS 3.18 22/02/2021: bla.md
        - Novità rilevanti introdotte in QGIS 3.20 21/06/2021: bla.md          
    - Elenco funzioni:
       - bla bla: bla.md
       - bla bla: bla.md
       - bla bla: bla.md
       - bla bla: bla.md
    - Mettiti alla prova con le espressioni di QGIS:
       - Provaci Tu: bla.md  
    - Corso di Formazione:
       - Corso di Formazione: bla.md
    - OpenDataSicilia:
        - OpenDataSicilia: bla.md
    -  Lavora con Noi:
        - Contribuire a HfcQGIS: bla.md
        - Supporter: bla.md
        - Parlano di noi: bla.md
    - Informativa privacy estesa:
        - Privacy Policy: bla.md

## Configuration
theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  palette:
    scheme: preference
  language: it
  features:
    - navigation.tabs
  palette:
    primary: green
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
    favicon: img/favicon.ico
  icon:
    logo: logo_hfc
plugins:
- search
- mkdocstrings

markdown_extensions:
- mkdocs-click
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.critic:
      mode: view
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.mark
- pymdownx.tilde
- pymdownx.smartsymbols
- admonition
- pymdownx.details
- pymdownx.tasklist:
      clickable_checkbox: true
      
## Custom theme additions
extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css      
      
google_analytics:
  - 'UA-122084242-1'
  - 'auto'